name: CI Build (under Windows)

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build all libraries
        shell: cmd
        run: gradlew.bat build --stacktrace
