name: Java CI with Gradle under Windows

on:
  pull_request:
    branches:
      - codegen_plugins

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and run tests
        shell: cmd
        run: gradlew.bat build --stacktrace
